config/routes.rb
Surveillance::Engine.routes.draw do
  namespace :admin do
    resources :surveys, shallow: true do
      resources :sections do
        resources :questions do
          member do
            match "edit-rules", action: "edit_rules", as: "edit_rules", via: [:put, :patch]
          end

          resources :options
          resources :questions
        end
      end

      resources :exports, only: [:show]
      resources :attempts
    end
  end

  resources :surveys, only: [:index, :show], shallow: true do
    namespace :response do
      resources :attempts, only: [:new, :edit, :update] do
        member do
          get "/complete", action: "complete", as: "complete"
        end
      end
      resources :partial_attempts, only: [:update]
    end
  end
end

app/models/surveillance/question.rb
module Surveillance
  class Question < ActiveRecord::Base
    include Surveillance::Field
    include ActionView::Helpers::SanitizeHelper

    has_many :questions, as: :parent, class_name: "Surveillance::Question",
      inverse_of: :parent, dependent: :destroy
    accepts_nested_attributes_for :questions, allow_destroy: true

    belongs_to :parent, polymorphic: true, inverse_of: :questions

    has_many :options, -> { ordered }, class_name: "Surveillance::Option",
      dependent: :destroy
    accepts_nested_attributes_for :options, allow_destroy: :true

    has_many :answers, class_name: "Surveillance::Answer",
                       dependent: :destroy

    has_many :settings, class_name: "Surveillance::FieldSetting",
      dependent: :destroy, inverse_of: :question
    accepts_nested_attributes_for :settings

    has_many :branch_rules, class_name: "Surveillance::BranchRule",
                            dependent: :destroy,
                            inverse_of: :question
    accepts_nested_attributes_for :branch_rules, allow_destroy: :true

    validates_presence_of :title

    delegate :survey, to: :parent

    scope :ordered, -> { order("surveillance_questions.id ASC") }

    def matching_rule_for answer
      branch_rules.find { |rule| rule.matches?(answer) }
    end

    def section
      parent_type == "Surveillance::Question" ? parent.parent : parent
    end

    def column_header
      header = if field.matrix? && field.display_other_field?(self)
        title + " - #{ field.settings.other.label }"
      else
        title
      end

      sanitize(header, tags: [])
    end
  end
end

app/views/surveillance/field/multiple_choices_matrix/_form.html.haml
.form-group
  %label.control-label{ required: question.mandatory }
    = "*" if question.mandatory
    = question.title.html_safe

  - if question.description.presence
    %p.help-block
      = question.description.html_safe

  .form-controls
    %table.table.table-striped.table-bordered.table-rounded
      %thead
        %tr
          %th
          - question.options.each do |option|
            %th
              = option.title

      %tbody
        - question.field.ordered_sub_questions.each do |sub_question|
          = f.fields_for :answers, (sub_question.field.answer_or_initialize_for(f.object)) do |fa|
            %tr.form-group{ class: ("has-error" if fa.object.errors.any?), data: { "sub-question-id" => sub_question.id } }
              %td
                %label.control-label
                  = sub_question.title.html_safe
                = fa.hidden_field :question_id, value: sub_question.id if fa.object.new_record?

              = fa.collection_check_boxes :option_ids, question.options, :id, :title do |input|
                %td.form-controls
                  %label
                    = input.check_box

app/views/surveillance/field/multiple_choices_matrix/_show.html.haml
= render partial: "surveillance/field/matrix/show", locals: { question: question }