config/routes.rb
Surveillance::Engine.routes.draw do
  namespace :admin do
    resources :surveys, shallow: true do
      resources :sections do
        resources :questions do
          member do
            match "edit-rules", action: "edit_rules", as: "edit_rules", via: [:put, :patch]
          end

          resources :options
          resources :questions
        end
      end

      resources :exports, only: [:show]
      resources :attempts
    end
  end

  resources :surveys, only: [:index, :show], shallow: true do
    namespace :response do
      resources :attempts, only: [:new, :edit, :update] do
        member do
          get "/complete", action: "complete", as: "complete"
        end
      end
      resources :partial_attempts, only: [:update]
    end
  end
end

app/models/surveillance/attempt.rb
module Surveillance
  class Attempt < ActiveRecord::Base
    include AASM

    has_many :answers, class_name: "Surveillance::Answer",
      foreign_key: 'attempt_id', dependent: :destroy, inverse_of: :attempt,
      before_add: :set_attempt_on_answers
    accepts_nested_attributes_for :answers

    belongs_to :survey, class_name: "Surveillance::Survey",
               inverse_of: :attempts

    belongs_to :user, polymorphic: true

    scope :includes_all, -> {
      includes(answers: [:question, :options, :content])
    }

    before_validation :ensure_access_token
    before_validation :filter_required_answers
    before_save :fill, if: :answers_filled_and_empty?

    aasm column: :state do
      state :empty, initial: true
      state :partially_filled
      state :completed

      event :fill do
        transitions from: [:empty, :partially_filled], to: :partially_filled
      end

      event :complete do
        transitions from: [:empty, :partially_filled, :completed], to: :completed
      end
    end

    def state_label
      if partially_filled?
        [
          I18n.t("surveillance.attempts.states.#{ state_name }"),
          I18n.t("surveillance.attempts.step", step: last_answered_section + 1),
        ].join(" - ")
      else
        I18n.t("surveillance.attempts.states.#{ state_name }")
      end
    end

    def fill_section(index, attributes)
      self.last_answered_section = index.to_i
      update_attributes(attributes)
    end

    def sections_to_answer
      @sections_to_answer ||= build_sections_to_answer_hash
    end

    def answer_to(question)
      id = question.kind_of?(Integer) ? question : question.id
      questions_answers[id]
    end

    def questions_answers
      @questions_answers ||= Hash[answers.map { |a| [a.question_id, a] }]
    end

    def to_param
      access_token
    end

    def answers_attributes=(attributes)
      processed = attributes.each_with_object({}) do |(key, val), hash|
        if val[:id].blank? && (answer = answer_to(val[:question_id].to_i))
          val[:id] = answer.id
        end

        hash[key] = val
      end

      # Clear `@questions_answers` cache so next time we call questions_answers
      # hash it will be fetched with latest data
      @questions_answers = nil

      assign_nested_attributes_for_collection_association(:answers, processed)
    end

    private

    def set_attempt_on_answers(answer)
      answer.attempt = self
    end

    def answers_filled_and_empty?
      empty? && answers.length > 0
    end

    def ensure_access_token
      self.access_token ||= Surveillance.unique_token
    end

    def filter_required_answers
      answers_to_delete = answers.reduce([]) do |delete, answer|
        delete << answer unless sections_to_answer[answer.question.section.id]
        delete
      end

      answers_to_delete.each { |answer| answers.delete(answer) }
    end

    def build_sections_to_answer_hash
      @sections = survey.sections.includes(questions: [:questions, :branch_rules])
      @sections.limit(last_answered_section + 1) if last_answered_section

      # Prepare sections to answer hash, with each section needing to be
      # answered by default
      sections_hash = Hash[@sections.map { |section| [section.id, true] }]
      # Iterate on each section and check if a matching branching rule is found.
      # If one is found, update the sections_hash according to the rule
      @sections.each do |section|
        next if sections_hash[section.id] == false

        matching_rule = section.questions.reduce(nil) do |rule, question|
          if !rule && (answer = answer_to(question))
            rule = question.matching_rule_for(answer)
          end

          rule
        end

        if matching_rule
          sections_hash.reduce(true) do |continue, (section_id, _)|
            if continue && section.id == section_id
              continue = false
            elsif section_id == matching_rule.section_id
              break
            elsif !continue
              sections_hash[section_id] = false
            end
            continue
          end
        end
      end

      sections_hash
    end
  end
end

app/controllers/surveillance/admin/attempts_controller.rb
module Surveillance
  module Admin
    class AttemptsController < Surveillance::Admin::BaseController
      expose(:survey, model: Surveillance::Survey, finder_parameter: :survey_id)
      expose(:attempts) { survey.attempts }
      expose(:attempt,  model: Surveillance::Attempt, attributes: :attempt_params)

      def index
        self.attempts = attempts.includes_all.page(params[:page])
        self.survey = Surveillance::Survey.all_with_answers.find(survey.id)
      end

      def list
      end

      def overview
      end

      def show
        self.attempt = Surveillance::Attempt.includes_all.find(attempt.id)
        self.survey = Surveillance::Survey.includes_all.find(attempt.survey_id)
      end

      def destroy
        attempt.destroy
        flash[:success] = flash_message(:success)
        redirect_to admin_survey_attempts_path(attempt.survey)
      end

      protected

      def attempt_params
        stong_parameters? ? params.require(:attempt).permit! : params[:attempt]
      end
    end
  end
end

app/controllers/surveillance/response/attempts_controller.rb
module Surveillance
  module Response
    class AttemptsController < Surveillance::Response::BaseController
      include Surveillance::AttemptsManagementConcern

      def new
        self.attempt = if previous_attempt
          if previous_attempt.completed?
            attempt_already_completed!(previous_attempt)
            return
          end

          flash[:success] = t("surveillance.attempts.previous_attempt_recovered")
          previous_attempt
        else
          Surveillance::Attempt.create!(
            last_answered_section: -1,
            ip_address: request.remote_ip,
            survey: survey
          )
        end

        redirect_to edit_response_attempt_path(attempt)
      end

      def edit
        attempt_already_completed!(attempt) and return if attempt.completed?
        self.attempt = Surveillance::Attempt.includes_all.find(attempt.id)
        store_attempt!(attempt)
      end

      def update
        if attempt.save!
          attempt.complete!
          if survey.last_page_description.presence
            redirect_to complete_response_attempt_path(attempt)
          else
            redirect_to survey_path(attempt.survey)
          end
        else
          flash[:error] = flash_message(:error)
          render "edit"
        end
      end

      def complete
      end
    end
  end
end

app/views/surveillance/admin/attempts/index.html.haml
%h1
  = "Sondage #{ survey.title }"
  = link_to admin_surveys_path, class: "btn btn-default pull-right" do
    %i.fa.fa-arrow-left
    Retour à la liste des sondages

%ul.nav.nav-tabs
  %li.active
    %a{"data-toggle" => "tab", :href => "#liste-reponses"}
      Liste des réponses
  %li
    %a{"data-toggle" => "tab", :href => "#recap"}
      Recapitulatif

.tab-content.inside-shadow

  #liste-reponses.tab-pane.fade.in.active
    %table.table.table-striped.table-hover
      %thead
        %tr
          %th= t("surveillance.attempts.answer_date")
          %th= t("surveillance.attempts.state")
          %th= t("surveillance.attempts.ip_address")
          %th
      %tbody
        - attempts.each do |attempt|
          %tr.attempt
            %td
              = l(attempt.created_at)
            %td
              = attempt.state_label
            %td
              = attempt.ip_address
            %td
              = link_to "Voir les réponses", admin_attempt_path(id: attempt.id), class: "btn btn-default"
              = link_to admin_attempt_path(id: attempt.id), class: "btn btn-danger", data: { confirm: t("flashes.surveillance/admin/attempts.destroy.confirm_message"), method: "delete" } do
                %i.fa.fa-times
                Supprimer
  = paginate attempts, theme: 'bootstrap3'

  #recap.tab-pane.fade

    - survey.sections.each do |section|
      %h1= section.title
      - section.questions.each do |question|
        = survey_overview_for question

app/views/surveillance/admin/attempts/list.html.haml
= link_to "Retour à la liste des sondages", admin_project_surveys_path(@project), class: "btn btn-default"
%br
%br
- @attempts.each do |attempt|
  .attempt
    .title.pull-left
      Répondu le :
    %label.pull-left
      = l(attempt.created_at)
    = link_to "Voir les réponses", show_admin_survey_attempts_path(@survey, attempt), class: "btn btn-primary pull-right"
    .clear

app/views/surveillance/admin/attempts/overview.html.haml
%h1= "Recapitulatif du sondage #{ @survey.title }"

- @survey.sections.each do |section|
  %h2= section.title
  - section.questions.each do |question|
    = survey_overview_for question

app/views/surveillance/admin/attempts/show.html.haml
.attempt
  .pull-right
    = link_to "Retour", admin_survey_attempts_path(attempt.survey), class: "btn btn-primary"

  %h2.title
    Questionnaire
    %strong
      = surround '"' do
        = attempt.survey.title

  .clearfix

  .attempt-additional-data.well
    .date
      = t("surveillance.attempts.answer_date")
      \:
      %strong= l(attempt.created_at)
    .state
      = t("surveillance.attempts.state")
      \:
      %strong= attempt.state_label

    .ip-address
      = t("surveillance.attempts.ip_address")
      \:
      %strong= attempt.ip_address

    .ip-address
      = t("surveillance.attempts.last_answered_section")
      \:
      %strong
        - if (last_answered_section = survey.sections[attempt.last_answered_section])
          = last_answered_section.title
        - else
          = t("surveillance.attempts.no_last_answered_section")


  %hr

  %h2
    Réponses

  %hr

  - survey.sections.each_with_index do |section, index|
    .attempt-section{ class: ("not-answered" if index > attempt.last_answered_section) }
      %h3
        = section.title

      - section.questions.each do |question|
        .survey-answer
          = survey_answer_for(attempt, question)
          %br
          %hr
          %br

%br
%hr
%br
= link_to "Retour", admin_survey_attempts_path(attempt.survey), class: "btn btn-primary"
%br
%br